.PHONY: clean All

All:
	@echo "----------Building project:[ teste - Debug ]----------"
	@cd "teste" && $(MAKE) -f  "teste.mk"
clean:
	@echo "----------Cleaning project:[ teste - Debug ]----------"
	@cd "teste" && $(MAKE) -f  "teste.mk" clean
